### ISSUE TITLE
"raw pp" should be "net pp" on the <rank command

### ISSUE THREAD

**Issue by kaimuu** [MaxOhn/Bathbot#10]
in this case 415.84 raw pp would mean one 415.84pp play since raw is just the raw value and net is the weighted value

![image](https://user-images.githubusercontent.com/36483368/123131551-12083f00-d44e-11eb-947c-eb63e16402a2.png)

**Comment by MaxOhn** [comment]
The meanings of "raw" are inverted depending what you focus at.
To add a given raw number to the total pp, you need to scale it up to accommodate for the weight adjustment.
But if you want to add the raw pp of a score to the total pp, you need to scale them down i.e. weight them.

In this context the value its displaying is really just a straight difference of `#(what's needed) - #(what's present)` and that simplicity is represented as "raw".
If I use "weighted", I implicitly shift the focus on a score whose pp were weight-adjusted.

Although both are correct, I don't think replacing "raw" would make things clearer so I'd say it's fine to keep as is.
