### ISSUE TITLE
BG minigame url error

### ISSUE THREAD

**Issue by M0RGaming** [MaxOhn/Bathbot#11]
After guessing close enough, the bot sends the url of the map, however there is an extra `/` after osu.ppy.sh/ causing the url to break
![image](https://user-images.githubusercontent.com/13577339/123216768-1ef55480-d487-11eb-8d62-80be34e445f0.png)

It looks like this issue also happens if they get the name exact. The issue doesnt happen if the full background is revealed or the game ends.

**Comment by MaxOhn** [comment]
Oh god that bug must've been in for an embarrassingly long time without me noticing 😄 
Fix incoming very soon, thanks for letting me know

**Comment by MaxOhn** [comment]
Fix is out 👌
