### ISSUE TITLE
Playcount and replays watched in the <osu command's graph are offset incorrectly if values are blank

### ISSUE THREAD

**Issue by Purplegaze** [MaxOhn/Bathbot#12]
![image](https://user-images.githubusercontent.com/25409695/132415381-4146ee17-b1ff-44bc-a1f8-34182f2b3cf2.png)
![image](https://user-images.githubusercontent.com/25409695/132415389-40a950d6-6313-4feb-9fb9-7265bd6c62b1.png)
I had a playcount spike as well as a replays watched spike at the same time in these graphs: note how they both happen in July, but the playcount graph ends there because I haven't played since then.

In the bot's graph, the replays watched graph is offset by 2 months, so the spikes appear to not happen at the same time.
![image](https://user-images.githubusercontent.com/25409695/132415271-ec61f461-afc4-41aa-8fe8-91b278007bf8.png)

**Comment by MaxOhn** [comment]
Turns out the api did not provide the last two months of playcount for some reason and I didn't account for it.
Pushing the fix soon.

Great catch, thanks :)
