### ISSUE TITLE
look into rkyv's Niche for twilight Id's

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#130]
> https://docs.rs/rkyv/latest/rkyv/with/struct.Niche.html for twilight

[Source message by @Badewanne3](https://discord.com/channels/741040473476694159/741212809987358722/1039969068024872970)

**Comment by MaxOhn** [comment]
Implemented through [`IdNiche`](https://github.com/MaxOhn/twilight/blob/b6af5d574889e113a156b9dd0b5be973fbbc4a31/twilight-model/src/id/niche.rs#L11)
