### ISSUE TITLE
Any way to undo roleassign?

### ISSUE THREAD

**Issue by hallowatcher** [MaxOhn/Bathbot#14]
I've accidentally bound roleassign to one of my message with a bunch of reactions **that I can't delete**.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/6265839/147489100-84a8644a-185c-4481-9f0a-077de96b5623.png">

Any way to undo this? I can't find it in the docs..

**Comment by hallowatcher** [comment]
Also like I mentioned, I can't delete the message which I bound it to because it already has roles
<img width="798" alt="image" src="https://user-images.githubusercontent.com/6265839/147489154-91db7ed7-7db3-4265-a766-8597ff9c5513.png">

**Comment by MaxOhn** [comment]
At the moment there's indeed no way for users to undo that other than deleting the message.
I'm putting it on my todo list and keep this open until I'm done implementing an undo version.

**Comment by MaxOhn** [comment]
The feature is now removed entirely so I guess that settles this issue aswell 😄
