### ISSUE TITLE
db error on LIKE while querying osu id

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#151]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1069369900088447026/image.png)
[Source message by @Badewanne3](https://discord.com/channels/741040473476694159/741057568297975928/1069369900289761400)

**Comment by MaxOhn** [comment]
The user must've suffixed a name with `\` which the database didn't appreciate in the query.

This is a non-issue because:
- usernames cannot end with `\`
- after the failed DB query, the osu!api is used as backup
