### ISSUE TITLE
Compare function displays wrong score grade for taiko

### ISSUE THREAD

**Issue by trollocat** [MaxOhn/Bathbot#16]
Any scores retrieved by the "$compare" function on a taiko map follows osu!standard rules of score grading, it assumes the map was FCed even tho it has misses. So my guess is it's interpreting "taiko misses" as "std 50s"

Here's an example of a play that gets an S grade even tho it has 44 misses
![image](https://user-images.githubusercontent.com/68620390/151716257-71de7f99-6dc4-439f-8910-678ef8fa4076.png)

**Comment by MaxOhn** [comment]
Fixed, thanks 🙏
