### ISSUE TITLE
panic while combining pfps

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#171]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1070965714279735306/image.png)
[Source message by @Badewanne3](https://discord.com/channels/741040473476694159/741057568297975928/1070965714745311252)

**Comment by MaxOhn** [comment]
The culprit badge: [Belgian osu! Cup 2022 Winner](https://osekai.net/badges/?badge=13407) of [Hexikey](https://osu.ppy.sh/users/10760701).
Likely reproducible on all badges owned by only one person, though.
