### ISSUE TITLE
incorrect personal best index

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#173]
> bathbot lied to me since it scorev1'd

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1071210871000399922/image.png)
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1071210871256256522/image.png)
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1071210871507927060/5218.png)
[Source message by @Hermit](https://discord.com/channels/741040473476694159/741057568297975928/1071210871986061363)

**Comment by MaxOhn** [comment]
Actually #179 is not completely correct, it should also consider mods.
