### ISSUE TITLE
Replace song preview to map preview in map command

### ISSUE THREAD

**Issue by aeongdesu** [MaxOhn/Bathbot#18]
map preview sites (bloodcat osu!preview based)
jmir1 (chimu.moe): http://jmir.xyz/osu/preview.html#BEATMAP_ID
aeongone (nerinyan.moe): https://osu.pages.dev/preview#BEATMAP_ID

---

It's not necessary, but I think it'll be better than song preview :)

**Comment by MaxOhn** [comment]
Not sure if I want to replace it completely but at least adding a map preview like that sounds pretty good

**Comment by MaxOhn** [comment]
Added with 87c26295a23b56b775a6daaa4ec60244fae13bd6
