### ISSUE TITLE
option to dictate score amount for /rank pp

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#184]
> rank pp command addition,  make it so you can choose how many scores u want it to calculate, for example you do /rank pp: number: 2

[Source message by @shatterdpixel](https://discord.com/channels/741040473476694159/741047663532834827/1073485291135967233)

**Comment by MaxOhn** [comment]
I think it should be doable by first binary searching a top play index, then if it's missing pp we go up to the top pp times two with another binary search and if it's too much pp we reduce the amount with another binary search.
So for `n` being the given amount of scores, it would look something like this
![rank_scores_amount_diagram](https://github.com/MaxOhn/Bathbot/assets/41148446/88c069d8-d2b6-4a39-b8b0-f7e86674c9f3)

All in all very complex to implement for a non-perfect solution to an arguably niche feature. Will be very low on my priority list.
