### ISSUE TITLE
claimname shouldnt accept "thelewa"

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#219]
> not sure if u wanna add but looks like this one was manually blocked

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741047663532834827/1077193763484618752/Screenshot_20230220_224224.jpg)
[Source message by @cd36](https://discord.com/channels/741040473476694159/741047663532834827/1077193763740459090)

**Comment by MaxOhn** [comment]
Same for the names "shavit" and "friendok"

**Comment by MaxOhn** [comment]
Although "thelewa" doesn't seem to be blocked manually but instead through the recent [highest-rank check](https://github.com/ppy/osu-web/blob/56e0626ad46053c3bbbf656e292ca50330e6704d/app/Libraries/UsernameValidation.php#L88-L94)
