### ISSUE TITLE
medal not bluffing shows as rarer than skylord

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#235]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1080020247886712862/Screenshot_20230228-075432.png)
[Source message by @TheMagicAnimals](https://discord.com/channels/741040473476694159/741057568297975928/1080020248218042439)

**Comment by MaxOhn** [comment]
It's sorting by `possession_rate` based on the rarity ranking which only includes two decimal places. Using `rarity` from medals instead should fix this.
