### ISSUE TITLE
commands whatif and rank dont coincide

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#236]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1080015533308645447/Screenshot_20230228-073534.png)
[Source message by @uyaz](https://discord.com/channels/741040473476694159/741057568297975928/1080015533593854013)

**Comment by MaxOhn** [comment]
Seems to be caused by the inherit error margin of the rank approximation for the `whatif` command. The algorithm will be slightly improved soon but for this issue specifically there is nothing to be done.
