### ISSUE TITLE
slash commands not working for numeric names

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#240]
> seems like the slash command gives an error if the username is just numbers

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1080510576872140800/IMG_20230301_182239.jpg)
[Source message by @yoru](https://discord.com/channels/741040473476694159/741057568297975928/1080510576897310831)

**Comment by MaxOhn** [comment]
Upstream issue https://github.com/twilight-rs/twilight/issues/2178
