### ISSUE TITLE
encorporate mapset description into /map embed

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#328]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741047663532834827/1101967426595324035/Screenshot_20230429-222426.png)
[Original message by @Badewanne3](https://discord.com/channels/741040473476694159/741047663532834827/1101967426851196938)

**Comment by MaxOhn** [comment]
Mapset descriptions are formatted through bbcode which would generally be too much of a pain to process properly for discord.
