### ISSUE TITLE
different mc values for prefix and slash command

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#353]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1104798736233799822/image.png)
[Original message by @Badewanne3](https://discord.com/channels/741040473476694159/741057568297975928/1104798736477081600)

**Comment by MaxOhn** [comment]
Cannot replicate. The last game of the match ended at 17:47 while the first matchcost message was calculated at 17:45 so the discrepancy between the two matchcosts seems correct.
