### ISSUE TITLE
ping skin url to check if it exists

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#367]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1105883222560227498/Screenshot_20230510-174416_Discord.png)
[Original message by @respektive](https://discord.com/channels/741040473476694159/741057568297975928/1105883222769946664)

**Comment by MaxOhn** [comment]
Instead of requiring a successful ping and thus further restricting potentially misconfigured self-hosts, it's probably sufficient to simply verifying that a fully valid URL was specified.
