### ISSUE TITLE
adjust rb content if index is specified

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#407]
> maybe it should say `57th most recent score in cd36's top100:`
> 
> could be a bit less confusing since i've seen a lot of ppl asking what rb[number] means in the past

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741047663532834827/1113445605797281852/image.png)
[Original message by @cd36](https://discord.com/channels/741040473476694159/741047663532834827/1113445606011187210)

**Comment by MaxOhn** [comment]
Closed by #474
