### ISSUE TITLE
hide hushhush solutions behind spoiler

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#415]
> maybe hush hush solutions should be hidden on `<mr` with a button to reveal the solution? i know some ppl that dont like being spoiled on the solutions and prefer figuring them out on their own

[Original message by @cd36](https://discord.com/channels/741040473476694159/741047663532834827/1116219899191238696)

**Comment by MaxOhn** [comment]
Likely best to make this an option in `/serverconfig` (`@megamix_craft`)
