### ISSUE TITLE
score rank on wrong side for profile compare

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#489]
> ranked score rank shows up on wrong profile

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1148970655342145696/image.png)
[Original message by @cyceph](https://discord.com/channels/741040473476694159/741057568297975928/1148970655556042923)

**Comment by MaxOhn** [comment]
Fixed upstream https://github.com/respektive/osu-score-rank-api/commit/a78ec1212c41aeb1b0eb6c83326d76045a589799
