### ISSUE TITLE
Tracker feature?

### ISSUE THREAD

**Issue by CCleanerShot** [MaxOhn/Bathbot#5]
Would be sick if the bot had a tracker/tracking feature to track people's top plays. I think it's known to cause future problems for bots, but this is up to you.

**Comment by MaxOhn** [comment]
I'd love to add that but unfortunately the api doesn't provide a nice way to collect the necessary data, at least to my knowledge. Especially with growing amount of Bathbot users, I currently wouldn't know how to feasibly implement tracking :(
Maybe I figure something out eventually or maybe the new api version will make it nicer but it'll definitely stay in the back of my mind.

**Comment by MaxOhn** [comment]
Tracking is implemented 🎉 
Has been for a while even but I had to solve one last mystery I couldn't crack.
With the commands `track`, `trackmania`, `tracktaiko`,  and `trackctb` one can track people in a channel, `untrack` lets you untrack people and `untrackall` untracks all people of a channel.
