### ISSUE TITLE
0 warmups might be more common than 2 for <mc

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#531]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741047663532834827/1159064733622747206/image.png?ex=651e86a6&is=651d3526&hm=3b75270c1618705cdbaed435d61112c73eaa17d91c6f6938036f68b246e52e8a&)
[Original message by @5joshi](https://discord.com/channels/741040473476694159/741047663532834827/1159064733828255796)

**Comment by MaxOhn** [comment]
Closed by #587
