### ISSUE TITLE
some mods shouldnt give pp

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#555]
> any cinema mod farmers

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1162393064900403250/image.png?ex=653bc5e6&is=652950e6&hm=03fce8366488883c3b94535c2ca544adfb9bf661b6269c0d4e0bd4b4943efc32&)
[Original message by @n_ada](https://discord.com/channels/741040473476694159/741057568297975928/1162393065101738024)

**Comment by MaxOhn** [comment]
osu!tools still calculates NM pp for mods like CN and lazer also displays NM pp while playing mods like AP so I think it's fine for the bot to also ignore these mods during performance calculation.
