### ISSUE TITLE
/map give inacturate pp amount

### ISSUE THREAD

**Issue by GGchung69** [MaxOhn/Bathbot#566]
/map map: https://osu.ppy.sh/beatmapsets/705423#osu/1492011 mods: dt shows 152 pp (which is the wrong pp amount)
![image](https://github.com/MaxOhn/Bathbot/assets/71476860/71f71656-c2de-40c3-8bef-c5db783269fd)
while /simulate map: https://osu.ppy.sh/beatmapsets/705423#osu/1492011 mods: dt n100: 1 shows 186 pp (which is the correct pp amount)
![image](https://github.com/MaxOhn/Bathbot/assets/71476860/0a52abd3-17dc-4062-9ef8-ab0e6a3a936a)

**Comment by kionell** [comment]
I can confirm that this bug exists

![Screenshot_2023-10-22-12-38-45-791-edit_com discord](https://github.com/MaxOhn/Bathbot/assets/43014304/0074b6e6-7544-4359-bf33-0049034b718b)

**Comment by MaxOhn** [comment]
Looks like the issue stems from osu-tools and its hitresult generation.

https://github.com/ppy/osu-tools/blob/93d81ec858edc936c3287747864df4e7776e6809/PerformanceCalculator/Simulate/OsuSimulateCommand.cs#L65-L77

Simulating the map [/b/1492011](https://osu.ppy.sh/beatmapsets/705423#osu/1492011) with 99% accuracy generates
- 97 n300
- 4 n100
- -2 n50

so the 50s count can be negative not only for an invalid miss count but also but with some other condition. Will look further into it.

**Comment by GGchung69** [comment]
should i rename this to "Bots give inaccurate pp amount when asking about percentage on short map"? because this happened to harumachi clover too
![Screenshot_2023-10-24-09-13-46-974_com discord](https://github.com/MaxOhn/Bathbot/assets/71476860/2f57b6df-76d1-4e86-936a-49a7bf7cac7f)

**Comment by MaxOhn** [comment]
I'm also suspecting it has to do with small hitobject amounts. The issue title isn't too important though, no worries 😄
