### ISSUE TITLE
Allow non 1.5x clock rate for lazer DT with custom adjust rates

### ISSUE THREAD

**Issue by tomm13** [MaxOhn/Bathbot#595]
If a score was set with 2.0x for example, bathbot would still show the 1.5x stats (pp and pp for fc)

**Comment by MaxOhn** [comment]
Would love to display lazer-specific values more accurately but sadly the osu!api provides very little to none of these values as of now. The bot is for the most part already prepared for these values but until they're included in the api it's not in my hands unfortunately.
