### ISSUE TITLE
bbcode in solution of Literal medal

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#596]
Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1188861676297130024/image.png?ex=659c10b7&is=65899bb7&hm=8304cdb11f5866c4275cb50232ba13ae8df8e44a68abe3f1b6bccd878583a2bc&)
[Original message by @glassive](https://discord.com/channels/741040473476694159/741057568297975928/1188861676485890138)

**Comment by MaxOhn** [comment]
Seems to be fixed on osekai's side.
