### ISSUE TITLE
can't invite bathbot

### ISSUE THREAD

**Issue by alisher711** [MaxOhn/Bathbot#6]
![image](https://user-images.githubusercontent.com/59560900/97087213-322af880-164a-11eb-8658-a9b8c6b1ab41.png)

**Comment by MaxOhn** [comment]
Yeah I'm aware of it, I've been in touch with discord support about it. 
Can't say how long until it will be resolved but hopefully soon.

**Comment by MaxOhn** [comment]
I finally got the issue resolved with discord staff, the bot can be invited again 🎉
