### ISSUE TITLE
wrong completion % for taiko convert

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#604]
> https://media.discordapp.net/attachments/692924139362713672/1195317096712773663/Screenshot_20240112_134315_Discord.png?ex=65b38ccb&is=65a117cb&hm=c4f9db71e397a3020e4d8c4f5741a3d07072b6113195048120b32a2897708270&=&format=webp&quality=lossless&width=762&height=588

[Original message by @- Somnolent -](https://discord.com/channels/741040473476694159/741057568297975928/1195318643689529384)

**Comment by MaxOhn** [comment]
Looks like the image was deleted by discord and the discord message displayed on the image was deleted as well.
Too little information for me to fix anything 😞
