### ISSUE TITLE
Potential osu!track Integration

### ISSUE THREAD

**Issue by Ameobea** [MaxOhn/Bathbot#637]
Hi! I'm Ameo - the creator + maintainer of [osu!track](https://ameobea.me/osutrack/).

I've been getting back into osu recently after a long time away and getting to know what tools are currently popular in the community.  I've seen that Bathbot is the go-to utility bot in the osu! Discord server and I've been finding it extremely useful.

I was wondering if you'd be interested in integrating some osu!track data or functionality into your bot in any way.  I know that the site is still used by a lot of players, and I've built an osu!track Discord bot myself in the past.  However, I think users would be served far better by having the commands available through your bot since it has a much larger presence.

Some ideas I had initially that might be good:

 * Use osu!track data to supplement the peak rank stat for users.  osu!track has peak ranks that are older + better than what the osu! site has for many users, and I think it would be cool to be able to provide that for users.  I could even give you a static DB dump of just old scores to avoid adding latency to your stats commands.
 * Add command to update users' osu!track profiles if explicitly requested.  That's basically what my Discord bot and in-game IRC bot do, and that functionality is also built into Tillerino with the `!u` command.
 * Or as an alternative, fire off requests to asynchronously update users' osu!track stats when they interact with the bot with `>r` or similar commands.  It would be a nice way to keep active users' osu!track profiles current without resorting to brute-force automatic refreshes.

Anyway, those were the ideas I had.  I'd be more to happy to implement any of these if you're interested - it's cool to see your bot is written in Rust.

If you're not interested, I completely understand as well; I'll continue being a happy user of your very useful bot :)

**Comment by MaxOhn** [comment]
Ohh I'm stoked reading this! Been an osu!track enjoyer for a long time already :D

Adding your peak rank data sounds pretty nice, will have a look into what's available and how the bot can display it.

I also like the idea of notifying your api about active users. Bathbot could store the timestamp of the last time it informed osu!track of a user's activity and send off an update whenever the last timestamp was longer than a day ago or some other threshold.

I should take a look at your api in general again, I think I skimmed over it years ago already but maybe now I find some better applications for it 👌 

Unfortunately, I'm currently swamped in things to work on so it might take me some time to get to this but I'm definitely looking forward to it.

**Comment by Ameobea** [comment]
That sounds great to me!  I'm more than happy to provide whatever you want on my end be that database dumps, new API endpoints, etc., just lmk.

> Bathbot could store the timestamp of the last time it informed osu!track of a user's activity and send off an update whenever the last timestamp was longer than a day ago or some other threshold.

That's very appealing to me; I'd love having a system like that in place.

And I'm also an experienced Rust programmer and would be more than happy to pitch in on the Bathbot side to implement things if you're interested, but I 100% understand if you prefer to avoid external code contributions.

**Comment by MaxOhn** [comment]
Notifying osutrack of user activity and using osutrack's peak data is finally implemented in #663 👍 

For now that's the only data I'm making use of but I imagine adding some graphs to the bot about historical user data should also be doable; will look into that at some later point.

**Comment by Ameobea** [comment]
Thank you so much for implementing this!  It will be great having a sort of auto-update feature for active users on osu!track, and I for one definitely look forward to flexing my 10-year-old 4-digit peak rank in Discord as well :)
