### ISSUE TITLE
remove osutracker :candle:

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#661]
> osutracker stuff should probably be removed

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1227120869344677929/Screenshot_20240409_145934_Discord.jpg?ex=6627405e&is=6614cb5e&hm=d394c7bc47ba6683591f174ae912d52486a870f52a36e7ad712b2433d69e4e36&)
[Original message by @cd36](https://discord.com/channels/741040473476694159/741057568297975928/1227120869545873440)

**Comment by MaxOhn** [comment]
Closed by #673
