### ISSUE TITLE
/ct /comparetop and <commonm/t/c only show standard plays

### ISSUE THREAD

**Issue by K0nomi** [MaxOhn/Bathbot#763]
when using one of these commands, it only compares top standard plays despite specifying a mode, and even this seems to only work sometimes. seems to happen regardless of what mode i have set as default in settings, and whether score data is set to lazer or stable
![image](https://github.com/user-attachments/assets/06c2e0fb-f2e5-4f0b-9518-1d38d562a88a)
the result of the image above should show multiple mania maps. also, my username was not specified in the 2nd slash command, which appears to be the reason for the inconsistency and is thus another bug

**Comment by MaxOhn** [comment]
Thanks for reporting it, will try to get to it soon 👍
