### ISSUE TITLE
adjust modded lb stars

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#768]
> weird discrepancy between star raitings?

Attachments:
![attachment](https://cdn.discordapp.com/attachments/741057568297975928/1269202762269200395/image.png?ex=66af34af&is=66ade32f&hm=3d8581a9fc49a96a1cb13c21c8b74d876898083996e51e9d69947140e051ea49&)
[Original message by @shatterdpixel](https://discord.com/channels/741040473476694159/741057568297975928/1269202762319659040)

**Comment by MaxOhn** [comment]
Turns out the bot was already showing the mod-adjusted stars if mods were given. That adjusted value is indeed wrong though sometimes.
