### ISSUE TITLE
Little formatting change for <common[gamemode]

### ISSUE THREAD

**Issue by trollocat** [MaxOhn/Bathbot#8]
![image](https://user-images.githubusercontent.com/68620390/107778140-738f0300-6d22-11eb-8225-df6432a1c0ed.png)
Right now it is a little confusing to know which player wins most of the time at a simple glance, this is because the 1st medal always goes to the left, and I think the most logical and visual way to represent this would be to have each column represent a player.

**Currently is:**
[1st Place]          [2nd Place]
🥇trollocat       🥈Whulf
🥇Whulf           🥈trollocat
🥇Whulf           🥈trollocat

**Suggested format:**
[trollocat]          [Whulf]
🥇trollocat       🥈Whulf
🥈trollocat       🥇Whulf
🥈trollocat       🥇Whulf

It is way more clear with the former that Whulf was the player with most wins and format looks cleaner :)

**Comment by MaxOhn** [comment]
Done :)
