### ISSUE TITLE
Discord embed not playing a gif when used in /avatar command.

### ISSUE THREAD

**Issue by valera456a** [MaxOhn/Bathbot#869]
When your osu! pfp is a gif, and you use the /avatar command, it does not play the gif, despite discord recognizing it as a gif (by letting you favourite it) and opening the file for the gif in the embed makes it play. The gif in question is also correct, since it's playing on the website.

It is not a discord problem explicitly, since i tried pasting the gif (both the original used for pfp and the serverside gif) and both play just fine.

![image](https://github.com/user-attachments/assets/2ca91fde-5aba-4c35-94f8-8913efae4372)

**Comment by MaxOhn** [comment]
The osu!api provides this url for your profile picture: <https://a.ppy.sh/4915980?1732912051.gif>
When pasting that into discord it does not play the gif by default, at least not for me. Same for the url without the hash and file type (<https://a.ppy.sh/4915980>).

Bathbot just uses whatever url is provided by the api and forwards it so this appears to be a discord issue.
