### ISSUE TITLE
Country CY is not supported

### ISSUE THREAD

**Issue by Def0lttGit** [MaxOhn/Bathbot#9]
Why :(
![image](https://user-images.githubusercontent.com/66359423/108825310-87aced00-75cb-11eb-921e-0f4567f88d9a.png)

**Comment by MaxOhn** [comment]
All the data for national top scores originates from the [huismetbenen](https://snipe.huismetbenen.nl/) website.
The website will lead you to a discord server where you can ask Mr Helix for your country to be added.
What you need is someone from your country that has supporter to join there and go through some simple steps.
And then once the website can provide data for your country I can whitelist it for the bot commands aswell :)

**Comment by MaxOhn** [comment]
Cyprus was added
